create table ARTICLE (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    USER_ID BIGINT NOT NULL,
    TITLE VARCHAR(50) NOT NULL,
    CONTENT VARCHAR(1000) NOT NULL,
    TYPE CHAR(2) NOT NULL,
    IMAGE_URL VARCHAR(100),
    CODE VARCHAR(10),
    RATING SMALLINT,
    
    constraint ARTICLE_PK PRIMARY KEY (ID)
);
