CREATE TABLE ARTICLE_CITE(
    ID BIGINT NOT NULL,
    CITED_ARTCILE_ID BIGINT NOT NULL,
    
    constraint ARTICLE_CITE_FK_1 FOREIGN KEY (ID) REFERENCES ARTICLE(ID),
    constraint ARTICLE_CITE_FK_2 FOREIGN KEY (CITED_ARTCILE_ID) REFERENCES ARTICLE(ID)
)